### ISSUE TITLE
trait `std::marker::Sync` is not implemented for `std::sync::mpsc::Receiver<rosc::OscMessage>`

### ISSUE THREAD

**Issue by ntonnaett** [suhr/xephys#1]
I can't compile xephys. Maybe you already know about this bug.

>    Compiling xephys v0.1.0 (https://github.com/suhr/xephys.git#e49bfab5)
> error[E0277]: `std::sync::mpsc::Receiver<rosc::OscMessage>` cannot be shared between threads safely
>    --> /home/nils/.cargo/git/checkouts/xephys-43cbc4530fa9fefb/e49bfab/src/main.rs:758:32
>     |
> 758 |     let active_client = client.activate_async((), process).unwrap();
>     |                                ^^^^^^^^^^^^^^ `std::sync::mpsc::Receiver<rosc::OscMessage>` cannot be shared between threads safely
>     |
>     = help: within `jack::ClosureProcessHandler<[closure@/home/nils/.cargo/git/checkouts/xephys-43cbc4530fa9fefb/e49bfab/src/main.rs:746:52: 756:6 out_port:jack::Port<jack::AudioOut>, rx:std::sync::mpsc::Receiver<rosc::OscMessage>, engine:Engine]>`, the trait `std::marker::Sync` is not implemented for `std::sync::mpsc::Receiver<rosc::OscMessage>`
>     = note: required because it appears within the type `[closure@/home/nils/.cargo/git/checkouts/xephys-43cbc4530fa9fefb/e49bfab/src/main.rs:746:52: 756:6 out_port:jack::Port<jack::AudioOut>, rx:std::sync::mpsc::Receiver<rosc::OscMessage>, engine:Engine]`
>     = note: required because it appears within the type `jack::ClosureProcessHandler<[closure@/home/nils/.cargo/git/checkouts/xephys-43cbc4530fa9fefb/e49bfab/src/main.rs:746:52: 756:6 out_port:jack::Port<jack::AudioOut>, rx:std::sync::mpsc::Receiver<rosc::OscMessage>, engine:Engine]>`

**Comment by suhr** [comment]
Fixed by https://github.com/suhr/xephys/pull/2.
